#' LAI partial PRS
#'
#' Estimates partial PRS according to local ancestry using the annoated VCF generated by annoLAI().
#' Provide betas for SNPs in annotated VCF (ensure they match direction of effect, can use mgData() and matchBETA() functions).
#' Can normalize partial PRS using PRS of ancestry references (Marnetto et al. 2020). For this to be valid, this reference PRS needs to be done on the same
#' set of SNPs. When combining partial PRS, Marnetto et al. 2020 recomend weighting by ancestry proportions.
#' @importFrom data.table fread
#' @importFrom stats sd
#' @param lai.vcf filepath to annoated LAI vcf
#' @param anc.code code of ancestry from LAI
#' @param betas vector of betas for weights
#' @param snps vector of snp ids to keep in estimation. Defaults to NA (no filtering)
#' @param norm normalize PRS against references. Defaults to FALSE
#' @param PRS.ref vector of PRS for references. Defaults to NA
#' @export

LAiPRS <- function(lai.vcf, anc.code, betas, snps=NA, norm=FALSE, PRS.ref=NA){

  #read in local ancestry annotated vcf
  vcf <- fread(lai.vcf, data.table = FALSE)
  #subset by snps
  if(length(snps) > 1){
    vcf <- vcf[vcf[,3] %in% snps,]
  }

  vcf <- vcf[10:ncol(vcf)]

  #convert to matrix
  vcf.target <- as.matrix(vcf)

  #convert to dosages, set to 0 if local ancestry does not match
  vcf.target <- ifelse(vcf.target == "1" | vcf.target == "2", vcf.target, 0)
  vcf.target <- gsub(paste0("1\\|1:.\\|", anc.code), 1, vcf.target)
  vcf.target <- gsub(paste0("1\\|1:",anc.code, "\\|."), 1, vcf.target)
  vcf.target <- gsub(paste0("0\\|1:.\\|", anc.code), 1, vcf.target)
  vcf.target <- gsub(paste0("1\\|0:",anc.code, "\\|."), 1, vcf.target)
  vcf.target <- gsub(paste0("1\\|1:",anc.code, "\\|", anc.code), 2, vcf.target)

  #calcuate PRS using provided betas
  vcf.target <- matrix(as.numeric(vcf.target), ncol = ncol(vcf.target))
  if(nrow(vcf.target) != length(betas)) stop("Vector of betas needs to match # of snps in vcf")
  vcf.target <- sweep(vcf.target, 1, betas, FUN="*")
  prs.target <- data.frame(ID=colnames(vcf.target), M_ANC= NA, M_TOTAL=NA, PRS_RAW=colSums(vcf.target),
                           stringsAsFactors = FALSE)

  #sum up number of markers
  M <- c()
  for(id in prs.target$ID){
    m_i <-length(vcf[[id]][grep(".....\\|1", vcf[[id]])]) + length(vcf[[id]][grep("....1\\|.", vcf[[id]])])
    M <- c(M, m_i)
  }

  prs.target$M_ANC <- M
  prs.target$M_TOTAL <- nrow(vcf.target)*2
  prs.target$M_TOTAL <- nrow(vcf.target)*2
  prs.target$PRS_AVG <- prs.target$PRS_RAW/prs.target$M_ANC

  if(norm == TRUE){
    #normalize PRS by PRS of references
    if(is.na(PRS.ref)) stop("If a PRS normalized by references is desired, provide vector of PRS for references using the same # of SNPs")

    ref.sd <- sd(PRS.ref, na.rm = TRUE)
    ref.mean <- mean(PRS.ref, na.rm = TRUE)
    prs.target$PRS_NORM <- (prs.target$PRS_RAW - ref.mean)/ref.sd
    prs.target$PRS_AVG_NORM <- (prs.target$PRS_AVG - ref.mean)/ref.sd
  }
  return(prs.target)
}
